### ISSUE TITLE
Spiky CRMDP Roadmap

### ISSUE THREAD

**Issue by jvmancuso** [jvmancuso/safe-grid-agents#30]
## Main road
- [x] Create new toy environments (@timorl's [repo](https://github.com/timorl/safety-gridworlds-gym))
- [ ] Clean up toy environments for use with Gym API
- [x] Refactor for use with Gym API (#32)
  - [x] Modify ai_safety_gridworlds_gym to fit our needs (@david-lindner's [fork](https://github.com/david-lindner/gym_ai_safety_gridworlds))
  - [x] Improve dependency management #31 
  - [x] Switch all code referencing envs to use Gym env
- [ ] Improved tooling for hyperparameter tuning (e.g. Ray)
- [ ] Estimate compute costs and finalize logistics
- [ ] Do experiments
  - [ ] Check if hparams tuned on Solver generalize to Cheater (vice versa too, but less important/rigorous)
- [ ] Investigate corrupt versions of harder environments
  - [ ] Maybe bigger / more realistic boat race
  - [ ] Maybe a modified Atari env
  - [ ] Maybe a modified MuJoCo env
  - [ ] Maybe modified BipedalWalker env

## Environments:
- [ ] TomatoWateringCRMDP
- [ ] TransitionBoatRaceCRMDP
- [ ] Toy environments
  - [ ] corrupt corners (satisfies our assumptions for guaranteed learnability)
  - [ ] corrupt path to goal (does not satisfy assumptions for guaranteed learnability)

## Experiments per env
- Baseline (learns corrupt reward)
- Cheater (learns with access to true reward)
- Solver (learns intended behavior from corrupt reward)

## Optional
- [ ] Generalize PPO #17
- [ ] Improve test coverage #29
